#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Secret","metadata":{"name":"argocd-secret"}})
#@overlay/match-child-defaults missing_ok=True
---
#@ if/end hasattr(data.values, "argocd"):
data:
  #@ if/end hasattr(data.values.argocd, "admin_password"):
  admin.password: #@ data.values.argocd.admin_password
  #@ if/end hasattr(data.values.argocd, "admin_passwordMtime"):
  admin.passwordMtime: #@ data.values.argocd.admin_passwordMtime
  #@ if/end hasattr(data.values.argocd, "server_secretkey"):
  server.secretkey: #@ data.values.argocd.server_secretkey