#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata": {"name": "ingress-nginx-controller"}})
---
#@overlay/replace
data:
  enable-opentracing: "true"
  zipkin-collector-host: zipkin.zipkin.svc.cluster.local
  log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $opentracing_context_x_b3_traceid'
