#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata": {"name": "ingress-nginx-controller"}})
---
#! Deployment => DaemonSet
kind: DaemonSet